### ISSUE TITLE
page load animation

### ISSUE THREAD

**Issue by koeenm** [fdnd-agency/deloitte#33]
De opdrachtgever had in de beschrijving gezet dat ze het een leuke toevoeging zouden vinden als er wat animaties in de website zaten

``` css
    @keyframes pageLoadAnimation {
        0% {
            transform: translateX(-50%);
            opacity: 0;
        }

        100% {
            transform: translateX(0);
            opacity: 100%;
        }
    }

    section {
        animation: 1s cubic-bezier(0.34, -0.04, 0.17, 0.98) pageLoadAnimation;
    }
```

Deze animatie is te zien wanneer je de pagina net hebt geladen
